### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by greeneggsandyaml** [MRLoghmani/relative-rotation#1]
Hello authors,

Thank you for your nice paper. I am trying to reproduce the results. I have run the code in the README twice, but I cannot get the result from the paper. Here are the outputs of the evaluations: 

```
---  RUN 1 ---
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,5,0.750817527795945
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,10,0.7981687377370831
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,15,0.8190102463483758
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,20,0.8284717680401134
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,25,0.8341399607586658
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,30,0.8354480052321779
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,35,0.8435578809679529
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,40,0.8461739699149771
```

```
---  RUN 2 ---
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,5,0.7590582079790713
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,10,0.8105515587529976
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,15,0.838805319380859
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,20,0.8470459995639852
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,25,0.8568999345977764
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,30,0.860649662088511
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,35,0.8644865925441465
rgbd-rr_resnet18_40_0.0003_1.0_64_1.0_0.1,40,0.8654894266405058

```

Do you know how I might be able to get the results reported in your paper?

**Comment by MRLoghmani** [comment]
First of all, thank you for your interest in our work! 

Could you please provide a few more details? 
- I assume you are trying to reproduce the results of the synHB->realHB scenario. Is this correct? Or are you working on the synROD->ROD scenario?
- Are you using the Dockerfile we provide? Are you using the same exact dependencies (same version) we specify?

In general, some variation in the results between two runs is expected. This is why our results are the average over three consecutive runs. However, using the Dockerfile we provide you should be able to get reasonably close to our results on average.
